apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-consumer.fullname" . }}
  labels:
    {{- include "api-consumer.labels" . | nindent 4 }}
data:
  BASE_URL: "/v1/group/"
  HOSTS: '{{ toJson .Values.hosts }}'
  RETRY_COUNT: "3"
  WAIT_BETWEEN_RETRIES: "10"